### Variables
@baseUrl = http://localhost:3000/api/v1
@contentType = application/json

@userId = {{get_all_response.response.body.data.users[0].id}}

@adminToken = {{login_response.response.body.data.tokens.accessToken}}

### ========================================
### ADMIN LOGIN (Get Token First)
### ========================================

### Login to get access token
# @name login_response
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@paas.com",
  "password": "Admin123!@#"
}

###

### ========================================
### USER MANAGEMENT ENDPOINTS (Admin Only)
### ========================================

### Get All Users
# Replace {{adminToken}} with actual admin token from login response
# @name get_all_response
GET {{baseUrl}}/admin/users
Authorization: Bearer {{adminToken}}
###

### Get User Statistics
GET {{baseUrl}}/admin/users/stats
Authorization: Bearer {{adminToken}}

###

### Get User by ID
# Replace USER_ID with actual user ID
GET {{baseUrl}}/admin/users/cmdheswbj000630vd60d2no0p
Authorization: Bearer {{adminToken}}

###

### Create New User
POST {{baseUrl}}/admin/users
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "name": "Test User",
  "email": "testuser@example.com",
  "password": "TestPass123!@#",
  "role": "USER"
}

###

### Update User
# Replace USER_ID with actual user ID
PUT {{baseUrl}}/admin/users/{{userId}}
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{

  "role": "USER",

}

###

### Change User Password
# Replace USER_ID with actual user ID
PATCH {{baseUrl}}/admin/users/{{userId}}/password
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

{
  "newPassword": "NewPassword123!@#"
}

###

### Toggle User Status (isActive true - flase)
# Replace USER_ID with actual user ID
PATCH {{baseUrl}}/admin/users/{{userId}}/toggle-status
Authorization: Bearer {{adminToken}}

###

### Delete User
# Replace USER_ID with actual user ID
DELETE {{baseUrl}}/admin/users/{{userId}}
Authorization: Bearer {{adminToken}}

###